# Generated by Django 4.1.1 on 2024-08-28 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('power', models.IntegerField()),
                ('year', models.IntegerField()),
                ('offer_date', models.DateTimeField(default=datetime.datetime.now)),
                ('view_count', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.brand')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('commented_date', models.DateTimeField(default=datetime.datetime.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.offer')),
            ],
        ),
    ]
