# Generated by Django 4.1.1 on 2024-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_vehicletype_offer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='year',
            field=models.DateField(),
        ),
    ]
