# Generated by Django 4.1.1 on 2024-08-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_offer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='year',
            field=models.IntegerField(),
        ),
    ]
