# Generated by Django 4.1.1 on 2024-08-29 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_offer_view_count_alter_offer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delete_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
