# Generated by Django 4.1.1 on 2024-09-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_offer_delete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delete_date',
        ),
    ]
